//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MwebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productID { get; set; }
        public string description { get; set; }
        public Nullable<int> catID { get; set; }
        public decimal price { get; set; }
        public string imageName { get; set; }
    
        public virtual category category { get; set; }
    }
}
