//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MwebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userID { get; set; }
        public string username { get; set; }
        public string fullname { get; set; }
        public int groupid { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
